allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@sentry/cli': true
  esbuild: true
  msw: true
  prisma: true
  sharp: true
  unrs-resolver: true

pnpm:
  onlyBuiltDependencies:
    - '@prisma/client'
    - '@prisma/engines'
    - '@sentry/cli'
    - esbuild
    - msw
    - prisma
    - sharp
    - unrs-resolver
  policies:
    minimumReleaseAge: false
